<template>
  <div class="defi-Pools">
    <h1 class="h1">
      <span class="grad-1">{{ $t("aside.my_pools") }}</span>
    </h1>
    <AppGuard>
      <div class="defi-Pools-wrapper">
        <div class="defi-Pools-section">
          <h2 class="h2">{{ $t("pool.title.uniswap") }}</h2>
          <div class="app-paragraphe">
            <p>
           Below, you'll find a list of the Uniswap pool NFTs in your possession. When you contribute liquidity to a trading pair on Uniswap, you are given an NFT that signifies your stake in that specific pool. This NFT can be loaned out on Defi Pool Share. To determine a suitable borrowing price for prospective buyers, it's important to know the percentage of the initial pool that you own, as this will give you an idea of your LP NFT's value.
            </p>
          </div>
          <div class="defi-Pools-list" v-if="myUniswapPools.length">
            <div class="grid-x2">
              <div :key="index" v-for="(pool, index) in myUniswapPools">
                <PoolItem v-bind="pool" :owned="true" />
              </div>
            </div>
          </div>
          <div class="defi-Pools-loading" v-else-if="isLoading">
            <AppBanner type="info" :loading="true">{{
              $t("global.loading")
            }}</AppBanner>
          </div>
          <div class="defi-Pools-empty" v-else>
            <AppBanner type="warning">{{ $t("pool.list.empty") }}</AppBanner>
          </div>
        </div>

        <div class="app-hr"></div>

        <div class="defi-Pools-section">
          <h2 class="h2">{{ $t("pool.title.lenders") }}</h2>
          <div class="app-paragraphe">
            <p>
        This list displays the NFT LP positions you have offered for borrowing or those that are currently being borrowed. You can track their status and, when the loan period concludes, retrieve your NFT LP. After the loan has been completed, you may choose to offer your liquidity for borrowing once more, for a specified duration. This allows you to efficiently manage your assets and share them with others in the marketplace.
            </p>
          </div>
          <div class="defi-Pools-list" v-if="myLendedPools.length">
            <div class="grid-x2">
              <div :key="index" v-for="(pool, index) in myLendedPools">
                <PoolLendedItem v-bind="pool" :owned="true" />
              </div>
            </div>
          </div>
          <div class="defi-Pools-loading" v-else-if="isLoading">
            <AppBanner type="info" :loading="true">{{
              $t("global.loading")
            }}</AppBanner>
          </div>
          <div class="defi-Pools-empty" v-else>
            <AppBanner type="warning">{{ $t("pool.list.empty") }}</AppBanner>
          </div>
        </div>

        <div class="app-hr"></div>

        <div class="defi-Pools-section">
          <h2 class="h2">{{ $t("pool.title.borrowers") }}</h2>
          <div class="app-paragraphe">
            <p>
             With the DeFi Pool Share Protocol marketplace, you can borrow NFT LP positions from others. During the loan period, you're able to claim the fees generated by the pool at any time using the smart contract. It's a simple way to utilize borrowed assets and benefit from their rewards. However, once the loan duration ends, you'll lose access to the LP position, and the NFT will return to the original owner. This system offers a straightforward and accessible way to engage with DeFi opportunities.
            </p>
          </div>
          <div class="defi-Pools-list" v-if="myBorrowedPools.length">
            <div class="grid-x2">
              <div :key="index" v-for="(pool, index) in myBorrowedPools">
                <PoolBorrowedItem v-bind="pool" :owned="true" />
              </div>
            </div>
          </div>
          <div class="defi-Pools-loading" v-else-if="isLoading">
            <AppBanner type="info" :loading="true">{{
              $t("global.loading")
            }}</AppBanner>
          </div>
          <div class="defi-Pools-empty" v-else>
            <AppBanner type="warning">{{ $t("pool.list.empty") }}</AppBanner>
          </div>
        </div>
      </div>
    </AppGuard>
  </div>
</template>

<script setup lang="ts">
import { useUserStore } from "~/stores/user";
import { UniPool } from "~/lib/data/types";

const userStore = useUserStore();
const { getMyPools } = useUniswap();
const { getLoansByLenders, getLoansByBorrowers } = useContractLending();

const myUniswapPools: Ref<UniPool[]> = ref([]);
const myLendedPools: Ref<UniPool[]> = ref([]);
const myBorrowedPools: Ref<UniPool[]> = ref([]);
const isLoading = ref(false);

async function refreshData() {
  if (!userStore.user) {
    return;
  }

  isLoading.value = true;
  myUniswapPools.value = [];
  myUniswapPools.value = await getMyPools(userStore.user.address);
  myLendedPools.value = [];
  myLendedPools.value = await getLoansByLenders(userStore.user.address);
  myBorrowedPools.value = [];
  myBorrowedPools.value = await getLoansByBorrowers(userStore.user.address);
  isLoading.value = false;
}

watch(
  () => userStore.user,
  async (newUser) => {
    if (newUser && newUser.address) {
      refreshData();
    }
  },
  {
    immediate: true,
  }
);

onMounted(() => {
  document.body.addEventListener("needRefreshData", refreshData);
});

onUnmounted(() => {
  document.body.removeEventListener("needRefreshData", refreshData);
});
</script>

<style lang="scss" scoped>
.defi-Pools {
  &-wrapper {
    display: flex;
    flex-direction: column;
    gap: calc(var(--main-padding) * 2);
  }
  &-list,
  &-empty,
  &-loading {
    margin-top: var(--main-padding);
  }
}
</style>
